apiVersion: apps/v1
kind: Deployment
metadata:
  name: wimb-deployment
  labels:
    app: wimb-d
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: wimb-p
  template:
    metadata:
      labels:
        app: wimb-p
        tier: wimb-tier
    spec:
      containers:
      - name: wimb-container
        image: crolvlee/wimb_test:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          name: wimb-container-port
---
apiVersion: v1
kind: Service
metadata:
  name: wimb-service
  labels:
    app: wimb-s
spec:
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: wimb-p
    tier: wimb-tier
  type: LoadBalancer